name: Run Gradle
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew clean build
      
    - name: SonarCloud Scan
      uses: jinguji/sonarcloud-gradle-github-action@v2
      env:
        SONAR_TOKEN: fe2e1284c1bdbeabb44f301d13f539ae52633ada
     
       
